databases:
  - name: postgres
    ipAllowList: []
    databaseName: marokkotravelconnection_render
    user: marokkotravelconnection_render

services:
  - type: web
    name: marokkotravelconnectiom_render   # Make sure this is the correct name you want
    env: ruby
    buildCommand: "./render-build.sh"       # Compile assets and other necessary build steps
    startCommand: "RAILS_ENV=production bundle exec puma -C config/puma.rb" 
    publishPath: public
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false