databases:
  - name: postgres
    ipAllowList: []
    databaseName: marokkotravelconnection_render
    user: marokkotravelconnection_render

services:
  - type: web
    name: marokkotravelconnection_render 
    env: ruby
    buildCommand: "bin/rails assets:precompile"  
    startCommand: "bin/rails server -p $port"
    publishPath: public
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

