databases:
  - name: postgres
    ipAllowList: []
    databaseName: marokkotravelconnection_render
    user: marokkotravelconnection_render

services:
  - type: web
    name: marokkotravelconnectiom_render
    env: ruby
    buildCommand: "bundle exec rake assets:precompile"
    startCommand: "bundle exec puma -C config/puma.rb"
    publishPath: public


   
 env: ruby
    buildCommand: "./render-build.sh"
    startCommand: "RAILS_ENV=production bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false


