# config/database.yml

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: 26052017
  host: localhost

development:
  <<: *default
  database: postgres

test:
  <<: *default
  database: postgres_test

production:
  <<: *default
  database: postgres_production
  username: postgres
  password: <%= ENV['POSTGRES_26052017'] %>
  host: localhost_producao

