# config/database.yml

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: 26052017
  host: localhost

development:
  <<: *default
  database: postgres

test:
  <<: *default
  database: postgres_test

production:
  adapter: postgresql
  encoding: unicode
  database: marokkotravelconnection_render
  username: marokkotravelconnection_render
  password: 26052017
  host: localhost
  port: 5432




