default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: mysecretpassword
  timeout: 5000

development:
  <<: *default
  database: marokkotravelconnection_development

test:
  <<: *default
  database: marokkotravelconnection_test

production:
  <<: *default
  database: marokkotravelconnection_production
  username: marokkotravelconnection
  password: <%= ENV['MAROKKOTRAVELCONNECTION_DATABASE_PASSWORD'] %>




